using TaskManagementAPI.Utilities;

namespace TaskManagementAPI.DTOs.Responses
{
    public class UserResponse
    {
        public int Id { get; set; }           // Auto-generated by DB
        public string UserName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public UserRole Role { get; set; } = UserRole.Guest;
    }
}
